# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ekHJxxhrIY9gKauiX_Mct3nmOA-6ABF4
"""

from flask import Flask, render_template, request
import joblib
import numpy as np

app = Flask(__name__)
model = joblib.load('huber_sales_model.pkl')

@app.route('/')
def home():
    return render_template('index.html')

@app.route('/predict', methods=['POST'])
def predict():
    try:
        ad_sales = float(request.form['ad_sales'])
        adspend = float(request.form['adspend'])
        sessions = float(request.form['sessions'])
        unit_session_percentage = float(request.form['unit_session_percentage'])

        features = np.array([[ad_sales, adspend, sessions, unit_session_percentage]])
        prediction = model.predict(features)[0]

        return render_template('index.html', prediction_text=f"Predicted Sales: {prediction:.2f}")
    except Exception as e:
        return render_template('index.html', prediction_text=f"Error: {str(e)}")

if __name__ == '__main__':
    app.run(debug=True)